version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/backend
      - ./tests:/tests
    depends_on:
      - backend
    command: pytest