services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    command: tail -f /dev/null  # Aktívan tartja a konténert
    stdin_open: true  # Interaktív mód
    tty: true         # Pszeudo-terminál hozzáadása

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - ./backend:/backend
      - ./tests:/tests
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    command: tail -f /dev/null  # Aktívan tartja a konténert
    stdin_open: true
    tty: true